GET http://127.0.0.1:5000/3cursosDisponiveis HTTP/1.1

###

GET http://127.0.0.1:5000/3cursosMatriculados/1 HTTP/1.1

###

GET http://127.0.0.1:5000/cursosDisponiveis HTTP/1.1

###

GET http://127.0.0.1:5000/cursosMatriculados/1 HTTP/1.1

###

GET http://127.0.0.1:5000/aulas/1 HTTP/1.1

###

GET http://127.0.0.1:5000/aula/1/1 HTTP/1.1